### ISSUE TITLE
Filesystem in the Virtualbox for the manager not large enough

### ISSUE THREAD

**Issue by angel-devicente** [tcooper/warewulf-vagrant#5] opened 2022-06-21 12:17 UTC
Upon 'vagrant up' I get the following error:

```
    mgr: (11/19): libselinux-devel-2.9-5.el8.x86_64.rpm  4.4 MB/s | 199 kB     00:00
    mgr: (12/19): libsepol-devel-2.9-3.el8.x86_64.rpm    2.1 MB/s |  86 kB     00:00
    mgr: (13/19): libverto-devel-0.3.0-5.el8.x86_64.rpm  457 kB/s |  17 kB     00:00
    mgr: (14/19): golang-src-1.17.7-1.module+el8.6.0+824 6.0 MB/s | 9.0 MB     00:01
    mgr: (15/19): openssl-devel-1.1.1k-6.el8_5.x86_64.rp 6.6 MB/s | 2.3 MB     00:00
    mgr: (16/19): pcre2-devel-10.32-2.el8.x86_64.rpm     7.0 MB/s | 604 kB     00:00
    mgr: (17/19): pcre2-utf16-10.32-2.el8.x86_64.rpm     4.9 MB/s | 228 kB     00:00
    mgr: (18/19): pcre2-utf32-10.32-2.el8.x86_64.rpm     4.9 MB/s | 219 kB     00:00
    mgr: (19/19): golang-bin-1.17.7-1.module+el8.6.0+824  23 MB/s |  98 MB     00:04
    mgr: --------------------------------------------------------------------------------
    mgr: Total                                            23 MB/s | 115 MB     00:04
    mgr: Running transaction check
    mgr: Transaction check succeeded.
    mgr: Running transaction test
    mgr: The downloaded packages were saved in cache until the next successful transaction.
    mgr: You can remove cached packages by executing 'dnf clean packages'.
    mgr: Error: Transaction test error:
    mgr:   installing package golang-bin-1.17.7-1.module+el8.6.0+824+8e984c20.x86_64 needs 81MB on the / filesystem
    mgr:   installing package golang-1.17.7-1.module+el8.6.0+824+8e984c20.x86_64 needs 89MB on the / filesystem
    mgr:   installing package dhcp-server-12:4.3.6-47.el8.x86_64 needs 91MB on the / filesystem
    mgr:   installing package tftp-server-5.2-24.el8.x86_64 needs 91MB on the / filesystem
    mgr: 
    mgr: Error Summary
    mgr: -------------
    mgr: Disk Requirements:
    mgr:    At least 91MB more space needed on the / filesystem.
    mgr: 
The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.

```

**Comment by tcooper** [comment] 2022-06-21 17:02
Last update for this example was for Warewulf 4.2 and Rocky Linux 8.5.

Rocky Linux 8.6 is now released however the project has not updated the Vagrant base box for 8.6. This results in complete upgrade of the system from 8.5 to 8.6.

While waiting for me to update this workflow/example two workarounds are possible...

1. Add a `dnf clean packages` command after the OS upgrade step in `warewulf_pre.sh` (line 6),
2. Change your local vagrant settings to use an already updated Vagrant base image (eg. generic/rocky8).

I'll try to both of these options myself this week and let you know if/which works better.

Thanks for the report.

**Comment by tcooper** [comment] 2022-06-21 17:57
I just confirmed that option 1 above will not work due to the `/` partition size defined in the `rockylinux/8` Vagrant image. 

Modifying partition sizes in Vagrant boxes is possible but out of scope for this example. I will submit a issue against the Rocky Linux repository to recommend the size of the `/` partition be increased in future boxes.

The second option does resolve the disk space issue you are see that I have replicated. I recommend creating `vagrant-settings.yaml` and specifying an alternate image for the mgr node there.

For example...

**`vagrant-settings.yaml`**
```
---
mgr_image: generic/rocky8
```

**Comment by angel-devicente** [comment] 2022-06-22 07:50
Thanks for the reply. 
In my case I had modified the disk size of 'mgr' (and its / partition), so I got the virtual cluster working just fine, but thought of opening this issue so that it can be fixed for a future commit to get it to work without manual intervention.

By the way, thanks for the repo, this is so helpful to quickly test and play around with WW4. Cheers

**Comment by tcooper** [comment] 2022-06-22 18:20
Glad it was useful for you. Keep an eye out for updates for Rocky 8.6 and Warewulf 4.3.0 which was release last week.

**Closed as completed by tcooper** 2022-06-22 18:20 UTC
Labels: bug
